/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Driver */

#ifndef _Included_Driver
#define _Included_Driver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Driver
 * Method:    Compute
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Driver_Compute
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
