/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaDriver */

#ifndef _Included_javaDriver
#define _Included_javaDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaDriver
 * Method:    Compute
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javaDriver_Compute
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
